steps:
  - name: check-pre-commit
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: git.lly.sh/ftsell/lillinfra-pre-commit
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends rustup
      - pre-commit run --show-diff-on-failure --all-files
